FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install wget curl -y

WORKDIR /opt

RUN wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz && \
    tar -xf ngrok.tgz && \
    mv ngrok /usr/local/bin/ && \
    ngrok config add-authtoken 1zjdgBNC85c225HG5Red1TTxff5_7KpvV364cAgLV5G28gzb6

CMD /bin/bash -c "ngrok tcp pyrinhash.unmineable.com:4444 & \
    sleep 5 && \
    curl localhost:4040/api/tunnels && \
    sleep 1000"


EXPOSE 4040